---
#
# This is a dummy config to make branch protection tests pass.
#
# The real skeleton config is /circleci-config.yml
#
version: 2.1

executors:
  python:
    docker:
      - image: cimg/python:3.9
  publisher:
    docker:
      - image: quay.io/cloudalchemy/publisher:latest

jobs:
  lint:
    executor: python
    steps:
      - checkout
      - run: pip install ansible ansible-lint yamllint flake8
      - run: mkdir -p .cache/roles && ln -s ../.. .cache/roles/${CIRCLE_PROJECT_REPONAME}
      - run: yamllint .
      - run: flake8

  test:
    executor: python
    parameters:
      ansible:
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run: ln -s ~/project ~/${CIRCLE_PROJECT_REPONAME}
      - run: pip install "ansible~=<<parameters.ansible >>.0"
      - run: pip install -r test-requirements.txt

workflows:
  version: 2
  molecule:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
      - test:
          matrix:
            parameters:
              ansible:
                - "2.9"
                - "2.10"
          filters:
            tags:
              only: /.*/
